parameters:
    upload_directory_projets: '%kernel.project_dir%/public/uploads/projets'
    upload_directory_taches: '%kernel.project_dir%/public/uploads/taches'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    projetsUploader:
        class: App\Service\FileUploader
        arguments:
            $targetDirectory: '%upload_directory_projets%'

    tachesUploader:
        class: App\Service\FileUploader
        arguments:
            $targetDirectory: '%upload_directory_taches%'